### ISSUE TITLE
Error in DateTimePicker

### ISSUE THREAD

**Issue by ArneRichter** [WildGums/Orc.Controls#187] opened 2020-04-28 12:25 UTC
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] WPF
I tried it here.
 - [ ] UWP
 - [ ] iOS
 - [ ] Android
 - [ ] .NET Standard
 - [ ] .NET Core

## Component

What component is this issue occurring in?
DateTimePicker

## Version of Library
? actual

## Version of OS(s) listed above with issue
Windows 10

## Steps to Reproduce
1. Choose in Orc.Controls Example DateTimePicker  
2. I have Format "[de-IT]dd.MM.yyyy HH:mm" - it means without seconds
3. Try to copy over menu

## Expected Behavior
copy the Date and Time

## Actual Behavior
- Runtime error in DateTimeFormatter.cs in line 62 in function "internal static string Format(DateTime dateTime, DateTimeFormatInfo formatInfo)"
"parts.Add(new KeyValuePair<int, string>(formatInfo.SecondPosition.Value, dateTime.Second.ToString(NumberFormatHelper.GetFormat(formatInfo.SecondFormat.Length))));"

you can solve it with:
                if (formatInfo.SecondPosition.HasValue)
                {
                    parts.Add(new KeyValuePair<int, string>(formatInfo.SecondPosition.Value, dateTime.Second.ToString(NumberFormatHelper.GetFormat(formatInfo.SecondFormat.Length))));
                }

- Runtime error in DateTimeFormatter.cs in line 96 in function "BuildFormatString(DateTimeFormatInfo formatInfo, List<KeyValuePair<int, string>> parts)"
"builder.Append(parts[5].Value);"

you can solve it with:
            if (parts.Count > 5)
            {
                builder.Append(parts[5].Value);
                builder.Append(formatInfo.Separator6);
            }

**Comment by GeertvanHorrik** [comment] 2020-04-28 13:37
Thanks for creating this ticket and thanks for even researching the solution. 

Would you be interested in doing a PR with the fix? We are happy to help out.

Pinging @mkhomutov  / @Averus-a

**Comment by Averus-a** [comment] 2020-04-28 13:43
Yes, the issue is relevant for current develop.

**Comment by GeertvanHorrik** [comment] 2020-05-01 08:33
@Averus-a , please go ahead and make the required changes.

**Comment by GeertvanHorrik** [comment] 2020-05-07 07:42
Should be fixed, thanks for reporting.

**Closed** 2020-05-26 10:31 UTC
